### PR TITLE
Add multitaper deconvolution

### PR DESCRIPTION
**Pull request by hfmark**
Adding this method also adds a dependency on mtspec; I'm not sure where that needs to be noted, though I did add it to the documentation.

### CODE REVIEW

**Comment by trichter** [comment]
I added some commits since you checked out master. Can you please rebase your branch onto master and force push it here.

```
git rebase master
git push -f
```

To get the tests running mtspec needs to be added in `.github/test_conda_env.yml`.

**Comment by hfmark** [comment]
Rebased, and I added mtspec to the yml file so hopefully the tests will run now :)

**Comment by trichter** [comment]
I renamed most of the deconvolve methods to be a bit more explicit.

I also changed again the low pass gauss parameter to be consistent with the other methods. The relation to the old gauss parameter is `gauss=2**0.5/glp`. So the `glp` parameter has units of `1/Hz` and the `gauss` parameter has units of `Hz`. The old default `glp=5/Hz` corresponds to `gauss=0.28Hz`. Is `gauss=0.5` as in the other methods be a sensible default here?

I did not dig any deeper into this method, but it looks sensible and the Q and L peaks appear at the correct position in the tests. Also the output of your notebook looks convincing. :smiley: 

Maybe you can check if your notebook still works well after my changes.

I eliminated one non-ascii char, because I recognized that the docs build failed.

From my point of view this PR is ready for merging.

**Comment by hfmark** [comment]
It all looks good to me! I just added better citations for the two papers I was working off of. The default of gauss=0.5 is fine - a slightly higher cutoff frequency might even be better for a lot of applications. I wrote most of this code to use on OBS data which required slightly more aggressive filtering.

Thanks again for reviewing all the code, and for finding so many sensible ways to refactor bits of it. My changing one bit of doc string shouldn't mess up the tests but I'll let them run again just in case before merging.

**Comment by trichter** [comment]
Thanks a lot for your contribution :+1:

**Pull request merged**
