### PR TITLE
Review - windows compatibility made easier :)

### PR DESCRIPTION
**Pull request by ThomasLecocq**
review for https://github.com/openjournals/joss-reviews/issues/1808

I made a small change to the documentation & travis CI config so normally windows could also be tested with fortran/toeplitz.

### CODE REVIEW

**Comment by trichter** [comment]
@ThomasLecocq, thanks for this insight! The toeplitz package installs successfully on travis. Unfortunately, the import is not yet working.

https://travis-ci.org/trichter/rf/jobs/656156204#L658

Could you test the toeplitz package locally on your Windows machine?

```
pip install toeplitz
toeplitz-runtests
```

**Comment by ThomasLecocq** [comment]
hey

>toeplitz-runtests

doesn't exist...

```
(rfenv) λ python
Python 3.6.7 (default, Dec  6 2019, 07:03:06) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import toeplitz
>>> toeplitz
<module 'toeplitz' from 'c:\\ProgramData\\Anaconda3\\envs\\rfenv\\lib\\site-packages\\toeplitz.cp36-win_amd64.pyd'>
```
seem OK

**Comment by trichter** [comment]
That is strange, maybe you need to restart your console for finding this command line script?
But it is not so important.
Does
```
from toeplitz import sto_sl, cto_sl
```
also work?

**Comment by ThomasLecocq** [comment]
yes

**Comment by ThomasLecocq** [comment]
```
C:\Users\TLecocq\Cmder
(rfenv37) λ python C:\ProgramData\Anaconda3\envs\rfenv37\Scripts\toeplitz-runtests
..
----------------------------------------------------------------------
Ran 2 tests in 0.037s

OK
```

**Comment by trichter** [comment]
OK, in this case I will merge your PR and investigate the travis problem directly in the toeplitz repository.

Thanks again!

**Pull request merged**
